set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports G]
set_property IOSTANDARD LVCMOS33 [get_ports H]
set_property IOSTANDARD LVCMOS33 [get_ports R]
set_property IOSTANDARD LVCMOS33 [get_ports V]
set_property PACKAGE_PIN Y9 [get_ports clock]
set_property PACKAGE_PIN AA11 [get_ports R]
set_property PACKAGE_PIN AB11 [get_ports G]
set_property PACKAGE_PIN V5 [get_ports B]
set_property PACKAGE_PIN Y5 [get_ports H]
set_property PACKAGE_PIN W5 [get_ports V]
set_property SLEW FAST [get_ports V]
set_property SLEW FAST [get_ports H]
set_property DRIVE 16 [get_ports H]
set_property DRIVE 16 [get_ports V]


set_property OFFCHIP_TERM NONE [get_ports B]
set_property OFFCHIP_TERM NONE [get_ports G]
set_property OFFCHIP_TERM NONE [get_ports H]
set_property OFFCHIP_TERM NONE [get_ports R]
set_property OFFCHIP_TERM NONE [get_ports V]
set_property PACKAGE_PIN F22 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
